steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/grab-repo/grab-web:latest'
      - '-f'
      - 'web/Dockerfile'
      - '--build-arg'
      - 'WEB_DEFAULT_API=https://grab-api-z7onh2ju2q-uc.a.run.app/'
      - '.'
    env:
      - 'DOCKER_BUILDKIT=1'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/grab-repo/grab-web:latest'
