steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/grab-repo/grab-api:latest', '-f', 'api/Dockerfile', '.']
    env:
      - 'DOCKER_BUILDKIT=1'
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/grab-repo/grab-api:latest'
